--VIEW DERSİ UZUN BİR SORGUNUN TEK SORGU HALİNE GETİRMEK
CREATE VIEW vw_PersonalInformation AS
SELECT CONCAT_WS(' ',P_NAME,P_SURNAME) AS "FULL_NAME",
       CASE -- BURADADA CASE WHEN TEKRARI YAPMIŞ OLDUK
       WHEN P_GENDER=0 THEN 'Erkek'
       WHEN P_GENDER=1 THEN 'Kadın'
       ELSE 'Belirtilmedi' END AS "Cinsiyet",
       P_BIRTHPLACE,
       P_TCNUMBER
FROM PERSONAL.HR.PERSON;
ALTER VIEW vw_PersonalInformation AS --ALTER YAPARAK GÜNCELLEME YAPTIK
SELECT CONCAT_WS(' ',P_NAME,P_SURNAME) AS "FULL_NAME",
       CASE
       WHEN P_GENDER=0 THEN 'Erkek'
       WHEN P_GENDER=1 THEN 'Kadın'
       ELSE 'Belirtilmedi' END AS "Cinsiyet",
       P_BIRTHPLACE,
       P_TCNUMBER,
       P_SALARY
FROM PERSONAL.HR.PERSON

SELECT * FROM vw_PersonalInformation

DROP VIEW vw_PersonalInformation --DROP YAPARAK SİLME İŞLEMİ GERÇEKLEŞTİREBİLİRİZ.
